### ISSUE TITLE
Prompt of the Day

### ISSUE THREAD

**Issue by dqian3** [dqian3/wikipedia-speedruns#62]
- [x]  Separate out prompt meta information (i.e. is public, what times it's ranked, etc) into separate table.
- [x] Add an endpoint for getting the current prompt of the day (by number) and link to that
- [x] Rewrite home page to be "Archive", "Other game modes", "Prompt of the day"
- [ ] #72

**Comment by dqian3** [comment]
Design:
Table for Day -> Prompt Number

Endpoint for current prompt (and time until expire)
Admin endpoint for assigning prompt to date (can be current), also endpoint for moving date

Manage page for next 2 weeks (just assign numbers, but in the future drag and drop)

**Comment by bricehalder** [comment]
What's the reasoning behind a separate table for prompt meta information? I'm assuming each prompt would have this information? 

Will we have multiple entries for a single prompt maybe? i.e. if a prompt is ranked multiple times, that would be a new entry into the meta info table?

**Comment by dqian3** [comment]
hmm, I don't think we'll ever have prompts ranked multiple times, but prompts don't necessarily have to be used for prompt of the day, and maybe a majority wouldn't.

 I also feel like it's cleaner to have a separate table mapping the date to the prompt id for prompt of the day. But I guess it'd be easier to write queries in one big table, i.e. if you want to know what day the prompt was ranked for.

**Comment by dqian3** [comment]
Oh I think the big thing is each date should only have one prompt, but I guess a `UNIQUE` constraint solves that

**Comment by bricehalder** [comment]
If not every prompt will have this extra info, then yeah I agree a separate table would be cleaner. New table with PK of date for each day
